name: Test Rust Implementation

on:
  push:
    branches: [ "master" ]
    paths:
      - 'rust/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'rust/**'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rust/src
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Test default/rust_crypto feature
      # to pass '--show-output' as a value, use '-- --show-output'
      run: cargo test -- --show-output

    - name: Test ring feature
      # to pass '--show-output' as a value, use '-- --show-output'
      run: cargo test --features ring -- --show-output
